name: Actions

on: push

jobs:
  Build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Build app
        run: |
          yarn install
          yarn build

      - name: Upload built files
        uses: actions/upload-artifact@v1
        with:
          name: dist-${{ matrix.os }}
          path: dist

  Release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ${{ matrix.os }}
    needs: Build

    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Download built files
        uses: actions/download-artifact@v1
        with:
          name: dist-${{ matrix.os }}
          path: dist

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            build/clipboard-resizer-*-mac.dmg
            build/clipboard-resizer-*-win.exe
            build/clipboard-resizer-*-win.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
